name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.4"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdec491e2859827f3395dac6a357e5ccf13eaaef8d9d0e4562c84397827870d0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
