name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.5"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0aad36a8ce8e7dce880edd581051955538647afcde83230e4c532674c28b0fc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
