name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.3"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f2b122a8e81f3f171f21433ed059e58ad354383132d447be19c5c210ee50272"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
