name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.1"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9a7419c88037c1137037b67abcb7b168a74135f5ba91d68446be2b97334d974"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
