name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d49a1539dc10b24d7163b610f2fb4c107c5a2e61e375ee38315e5151f9c2e2b4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
