name = "Small Iron Pack 3"
author = "taffer3935"
version = "1.3.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9caa2a68d238a8a5830735ae83a1973c5236bf1ddd7e1e8f49037c0eddadecc0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
